API仕様書の作成、HTML３つの作成
shushushun/demo pull request #3
Opened 2022-06-19 06:25 UTC by shushushun

API仕様書はhttps://qiita.com/teinen_qiita/items/e440ca7b1b52ec918f1bをもとに作成しました。

HTMLはAPIで指定している動作が、それぞれのページで動くことを想定しています。

ご確認のほどよろしくお願いいたします。

2022-06-19 06:50 UTC, repenguin22 commented
@shushushun 
ごめん。HTMLはそういう意味ではなくて、APIのHTML化したものを貼ってねって意味でした。
こっちで追加しておきました。開いたらAPIのドキュメントが見れると思います。
画面サンプルは別にいらないです。

### 修正必須
- resources/templatesを削除
- resources/docsを削除
- resources/OpenAPI/OpenAPISpecification.txtをyamlファイルに変更してください。

### Git運用について

あとPRのブランチの名前は基本的にGitFlowに従いましょう。(今回はこのままで大丈夫です)
ブランチ運用についてはこのリポジトリでは、全部mainへのPRで良いです。
https://www.atlassian.com/ja/git/tutorials/comparing-workflows/gitflow-workflow

大まかに以下のようにPRの名前をつけましょう。ほとんどのものが「feature/***」のようなブランチ名になります。
- featureブランチ(開発中に使用する機能に関するブランチ) 例：feature/add_sample_html
- hotfixブランチ(本番リリース済みのもので緊急の修正を入れるもの) 例：hotfix/add_sample_html

2022-06-19 06:51 UTC, repenguin22 commented
PRで以下を設定しましょう。
- Reviewers
- Assignees
- Labels(必要に応じて)

2022-06-19 09:41 UTC, shushushun commented
フォルダ削除、ファイル名変更しました。
またPRの設定についても変更しました。

ブランチ名については以降気をつけます。

2022-06-19 11:35 UTC, repenguin22 requested changes
一旦いくつか修正お願いします。

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        '200': # HTTP status
全体的な話になりますが、異常系(HTTPステータスだと400,500系)を追加してください。
細かすぎると動きにくいと思うので、今回は404と500だけで良いです。

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  - id: 2
typo ここだけidになっています。

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  deadline: 2022-9-30
これは設計のやり方にもよりますが、ユーザのタスクを取得する場合のパスは以下のようにするのが正しいです。
- ユーザに紐づくタスク一覧：GET /users/{user_id}/tasks/
- タスク詳細：GET /users/{user_id}/tasks/{task_id}

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        - name: userId
キャメルとスネークが混合しています。統一しましょう。

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +      summary: Create a new Employee
userなのかemployeeなのかどちらですか？揃えましょう。

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +            example:
ユーザを作成するときにユーザIDを必須にしますか？
通常DBで自動採番するものだと思います。
タスクを作成するときも同様です。

2022-06-19 11:35 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +      responses:
ここらへんのHTML出力がバグっているのでコードが間違っていると思います。

2022-06-19 11:42 UTC, repenguin22 commented
ちなみにドキュメントの生成には以下を使用しています。
https://www.npmjs.com/package/redoc-cli

2022-06-23 12:29 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        - name: userId
スネークに統一しました。

2022-06-23 12:34 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  deadline: 2022-9-30
> ユーザに紐づくタスク一覧：GET /users/{user_id}/tasks/
→こちらのみ、指摘事項反映しました。

>タスク詳細：GET /users/{user_id}/tasks/{task_id}
→こちらは一旦、搭載していません。

2022-06-23 12:35 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        '200': # HTTP status
404と500を追加しました。
参考：https://note.com/shift_tech/n/n80c7c346571c

2022-06-23 12:36 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +            example:
一旦ユーザIDとタスクIDについて必須から外しました。

2022-06-24 11:19 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        '200': # HTTP status
> 作成で404はありえません。

”作成”の意味はPOSTするときって意味であってますか？
GETするときに見つからないのはわかるが、POSTでNOTFOUNDはありえないという意味ですかね。

2022-06-24 11:21 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  - id: 2
＜メモ＞
ローカルで修正済み

2022-06-24 11:22 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  deadline: 2022-9-30
＜メモ＞
ローカルで修正済み

2022-06-24 12:00 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +            example:
＜メモ＞
（おそらくもともとパラメータが設定されていなかったので、）
ローカルにでPOSTのメソッドについて、パラメータの追加済

2022-06-24 12:47 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        '200': # HTTP status
はい。基本的にそうです。
作成はPOSTかPUTです。
404は対象のリソースが見つからないということです。
単体のリソースを新規作成するのに見つからないということはありませんよね？
これが依存関係のある前提リソースがあって、それをもとに作成するような場合は404を返すように設計することもあります。

2022-06-24 12:54 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +        '200': # HTTP status
一旦POSTの４０４の削除をし、再コミットしました。

2022-06-24 12:54 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  - id: 2
再コミット、プッシュしました。

2022-06-24 12:55 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  deadline: 2022-9-30
再コミット、再プッシュしました。

2022-06-24 12:55 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +            example:
再コミット、再プッシュしました。

2022-06-24 13:07 UTC, repenguin22 commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  deadline: 2022-9-30
exampleがobjectを返していてlistを返していないので修正してください。

2022-06-24 14:31 UTC, shushushun commented
>javaクラスが追加されていますが、PRを分けてください。
このPRはドキュメントだけにしてください。

機能ごとの修正（もしくはドキュメントごと）にブランチを切って、それぞれを各プルリクエストに対応させるイメージですか？
今回はドキュメントのを更新していくため専用のブランチ（命名はおかしいけどpull_requestブランチ）にドキュメント以外のコミット＋プッシュしてしまったことが問題ってことであってますかね。

2022-06-24 20:03 UTC, repenguin22 commented
> 機能ごとの修正（もしくはドキュメントごと）にブランチを切って、それぞれを各プルリクエストに対応させるイメージですか？
> 今回はドキュメントのを更新していくため専用のブランチ（命名はおかしいけどpull_requestブランチ）にドキュメント以外のコミット＋プッシュしてしまったことが問題ってことであってますかね。

はい。そうです。

2022-07-10 06:43 UTC, shushushun commented on src/main/resources/OpenAPI/OpenAPISpecification.yml
> +                  deadline: 2022-9-30
objectからarrayを返すように変更

2022-07-10 07:05 UTC, shushushun commented
> javaクラスが追加されていますが、PRを分けてください。
このPRはドキュメントだけにしてください。

git remote --cached　によるpull_requestブランチからの削除済み

2022-07-10 08:15 UTC, repenguin22 approved these changes
一旦これで良いと思います。

2022-07-10 08:16 UTC, merged